### ISSUE TITLE
Documentation: adjust directory

### ISSUE THREAD

**Issue by perlchamp** [MaxxKra/Abfallerinnerung#2]
hallo,
tolle Arbeit !
Ich bin gerade dabei, das alles zu installieren und zu konfigurieren. Ich bin auch noch ganz am Anfang. Hierbei hatte ich eine Fehlermeldung, die ich auch sofort beheben konnte. Diese Nachricht dient also in erster Linie zu deiner Information.
Meine configuration.yaml sieht momentan so aus:
```
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:  
  themes: !include_dir_merge_named themes
  extra_module_url: !include extra_modules.yaml

automation: !include automations.yaml
influxdb: !include influxdb.yaml
scene: !include scenes.yaml
scrape: !include scrapes.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
template: !include templates.yaml
waste_collection_schedule: !include waste_collections.yaml
```

Der Inhalt der waste_collections.yaml:
```
sources:
  - name: ics
    args:
      file: "/local/abfallentsorgung/Abfuhrtermine.ics"
```

Der Fehler entstand dadurch (so steht es in deiner Anleitung) :
`www/abfallentsorgung/Abfuhrtermine.ics`

Also einfach abändern. Vielleicht willst du deine Anleitung bezüglich des sogenannten yaml-breakings ebenfalls anpassen.

Hier ist ein Text dazu:
```
Installation
    1. HA → HACS→ in die Suchmaske 'wast' eintragen, und den Eintrag 'Waste Collection Schedule' auswählen → herunterladen → Version auswählen, hier: 2.6.0 → Installationsverzeichnis: '/config/custom_components/waste_collection_schedule' → herunterladen → HA neu starten
    2. Zur Einrichtung des Abfallkalenders gibt es mehrere Möglichkeiten. Hier wird die Variante mittels einer ics-Datei beschrieben. Im '/config/www'-Verzeichnis nun zuerst den Unterordner 'abfallentsorgung' bzw. 'muell' anlegen, und dort die entsprechende ics-Datei, hier: 'Abfuhrtermine.ics', ablegen. Dazu :
    • in Studio Code Server auf den soeben angelegten Ordner 'abfallentsorgung' rechtsklicken, und die Option 'Upload…' auswählen
    • die entsprechende .ics-Datei auswählen → öffnen 
    3. Im '/config'-Verzeichnis die leere Datei 'waste_collections.yaml' anlegen.
    4. den nachfolgenden Eintrag an das Ende der 'configuration.yaml' platzieren und anschließend speichern :
waste_collection_schedule: !include waste_collections.yaml
    5. die Datei 'waste_collections.yaml' in Studio Code Server öffnen, die nachfolgenden Codezeilen einfügen, und anschließend mittels strg+s speichern :
sources:
  - name: ics
    args:
      file: "/local/abfallentsorgung/Abfuhrtermine.ics"

    6. HA → Entwicklerwerkzeuge → Konfiguration prüfen → alles in Ordnung → neu starten 
    7. Überprüfung: HA → Entwicklerwerkzeuge → in der Menüleiste - unterhalb der Titelleiste - den Eintrag 'Zustände' aufrufen → entsprechenden Sensor suchen, draufklicken und anschauen. Ist also dieser Zustand (als Sensor) dort zu sehen, dann war die Installation erfolgreich. Herzlichen Glückwunsch !
```

So long
Pc
